---
- name: "Custom VM"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-misc"
    - role: "roles/configure-kitty"
    - role: "roles/configure-zsh"
    - role: "roles/configure-home"
      users:
        - username: "{{ ansible_user_id }}"